improve comments, etc

diff --git a/.github/workflows/ParseRelaysDotDatInteractive.yaml b/.github/workflows/ParseRelaysDotDatInteractive.yaml
--- a/.github/workflows/ParseRelaysDotDatInteractive.yaml
+++ b/.github/workflows/ParseRelaysDotDatInteractive.yaml
@@ -3,13 +3,16 @@ name: ParseRelaysDotDatInteractive
 
 on:
   workflow_dispatch:
+    # you cannot upload files directly via workflow_dispatch
+    # so we use an interactive step to upload the file
 
 jobs:
   ParseRelaysDotDatInteractive:
     runs-on: ubuntu-latest
     steps:
-      - name: Example Interactive Inputs Step
+      - name: Interactive File Upload Step
         id: interactive-inputs
+        # NOTE: this requires linux:
         uses: boasihq/interactive-inputs@v2
         with:
           ngrok-authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
@@ -17,7 +20,7 @@ jobs:
             fields:
               - label: uploaded-file
                 properties:
-                  display: Upload Relays.dat file to parse # Optional: if not specified, the title for the field will not be displayed on the portal
+                  display: Upload Relays.dat file to parse
                   type: file
                   required: true
                   description: Select a Relays.dat file to be uploaded to the runner for processing
@@ -29,6 +32,12 @@ jobs:
         run: |
             curl -O https://bigfix-wiki.hcltechsw.com/wikis/form/anonymous/api/wiki/9800bed4-8101-452b-930b-807aed3eb996/page/e2ee048f-bc56-4798-ba0b-e57c08a23160/attachment/71245215-dbd5-4f4a-b926-14afdd9d8f3c/media/ParseRelaysDotDat.exe
             ls
+            if [[ "$(shasum -a 256 ParseRelaysDotDat.exe)" == *"dc80ce17015cca3cc477c7ff53d334c6d8a9d0e915ffa255a1b178afb383631b"* ]] ; then
+              echo 'Integrity Check Passed'
+            else
+              echo 'Integrity Check Failed'
+              exit 1
+            fi
 
       - name: List the uploaded files in the directory
         shell: bash
